### ISSUE TITLE
Explanation for fork in the README

### ISSUE THREAD

**Issue by SirVer** [vi/rust-websocket#1]
This is a fork of the original crate and has even been republished to crates.io. This is quite confusing and no explanation is given on crates.io, the homepage or the README. 

Please state somewhere why you felt the need to fork the original project and what your fork has to offer over the original one and why you republished it one crates.io.

Right now you make it much harder for people to decide which crate to use: the original one (more downloads) or yours (higher version number).

**Comment by vi** [comment]
Because of my (and others) pull requests were not reviewed (for about 4 months) and the author failed to reply (2 month ago) an explicit e-mail about future of rust-websocket project.

On crates.io because of I want `cargo install websocat` to be more useful and `rust-websocket` abandonment prevents it.

If `rust-websocket` project awakes then maybe I can switch websocat back from `websocket-vi` to `websocket`.

What notice for the description/README do you propose for this?

**Comment by SirVer** [comment]
Those are excellent reasons - please make them discoverable. For example by adding them to the README of your repository and - if possible - by adding this information to crates.io.
